# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
image:
  repository: eu.gcr.io/gardener-project/gardener/extensions/shoot-networking-problemdetector
  tag: latest
  pullPolicy: IfNotPresent

serviceName: shoot-networking-problemdetector
replicaCount: 1

resources:
  requests:
   cpu: "30m"
   memory: "64Mi"
  limits:
   cpu: "50m"
   memory: "128Mi"

controllers:
  lifecycle:
    concurrentSyncs: 5
  healthcheck:
    concurrentSyncs: 5
  ignoreOperationAnnotation: false

ignoreResources: false

vpa:
  enabled: true
  resourcePolicy:
    minAllowed:
      cpu: 30m
      memory: 64Mi
  updatePolicy:
    updateMode: "Auto"

gardener:
  version: ""

## settings for metrics, e.g. scraping by seed-prometheus
##
metrics:
  ## enable metrics scraping
  ##
  enableScraping: true

networkProblemDetector:
  defaultPeriod: 15s
#  pspDisabled: false # pod security policy
#  pingEnabled: false
