# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-extension-{{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.ignoreResources }}
  annotations:
    resources.gardener.cloud/ignore: "true"
{{- end }}
  labels:
    app.kubernetes.io/name: gardener-extension-{{ .Values.serviceName }}
    helm.sh/chart: gardener-extension-{{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-{{ .Values.serviceName }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/configmap-extension-shoot-networking-problemdetector.config: {{ include (print $.Template.BasePath "/extension-config.yaml") . | sha256sum }}
        {{- if .Values.egressFilter.oauth2Secret }}
        checksum/secret-extension-shoot-networking-problemdetector.oauth2: {{ include (print $.Template.BasePath "/secret-oauth2.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.imageVectorOverwrite }}
        checksum/configmap-extension-imagevector-overwrite: {{ include (print $.Template.BasePath "/configmap-imagevector-overwrite.yaml") . | sha256sum }}
        {{- end }}
        {{- if and .Values.metrics.enableScraping }}
        prometheus.io/scrape: "true"
        # default metrics endpoint in controller-runtime
        prometheus.io/port: "8080"
        {{- end }}
      labels:
        app.kubernetes.io/name: gardener-extension-{{ .Values.serviceName }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if gt (int .Values.replicaCount) 1 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - gardener-extension-{{ .Values.serviceName }}
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - {{ .Release.Name }}
            topologyKey: "kubernetes.io/hostname"
      {{- end }}
      priorityClassName: gardener-extension-{{ .Values.serviceName }}
      serviceAccountName: gardener-extension-{{ .Values.serviceName }}
      containers:
      - name: gardener-extension-{{ .Values.serviceName }}
        image: {{ include "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-shoot-networking-problemdetector
        - --config=/etc/shoot-networking-problemdetector/config.yaml
        {{- if .Values.egressFilter.oauth2Secret }}
        - --oauth2-config-dir=/etc/shoot-networking-problemdetector/oauth2
        {{- end }}
        - --lifecycle-max-concurrent-reconciles={{ .Values.controllers.lifecycle.concurrentSyncs }}
        - --healthcheck-max-concurrent-reconciles={{ .Values.controllers.healthcheck.concurrentSyncs }}
        - --ignore-operation-annotation={{ .Values.controllers.ignoreOperationAnnotation }}
        - --leader-election-id={{ include "leaderelectionid" . }}
        - --gardener-version={{ .Values.gardener.version }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EXTENSION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.imageVectorOverwrite }}
        - name: IMAGEVECTOR_OVERWRITE
          value: /charts_overwrite/images_overwrite.yaml
        {{- end }}
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | trim | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: shoot-networking-problemdetector-config
          mountPath: /etc/shoot-networking-problemdetector
          readOnly: true
        {{- if .Values.egressFilter.oauth2Secret }}
        - name: shoot-networking-problemdetector-oauth
          mountPath: /etc/shoot-networking-problemdetector/oauth2
          readOnly: true
        {{- end }}
        {{- if .Values.imageVectorOverwrite }}
        - name: extension-imagevector-overwrite
          mountPath: /charts_overwrite/
          readOnly: true
        {{- end }}
      volumes:
      - name: shoot-networking-problemdetector-config
        configMap:
          name: extension-shoot-networking-problemdetector.config
          items:
            - key: config.yaml
              path: config.yaml
      {{- if .Values.egressFilter.oauth2Secret }}
      - name: shoot-networking-problemdetector-oauth
        secret:
          secretName: extension-shoot-networking-problemdetector.oauth2
      {{- end }}
      {{- if .Values.imageVectorOverwrite }}
      - name: extension-imagevector-overwrite
        configMap:
          name: gardener-extension-{{ .Values.serviceName }}-imagevector-overwrite
          defaultMode: 420
      {{- end }}
