{{- if .Values.egressFilter.oauth2Secret }}
apiVersion: v1
kind: Secret
metadata:
  name: extension-shoot-networking-problemdetector.oauth2
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- range $key, $val := .Values.egressFilter.oauth2Secret }}
  {{ $key }}: {{ b64enc $val }}
{{- end }}
{{- end }}